version: "3.9"

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        networks:
            - rmq
        ports:
            - 5672:5672
            - 15672:15672

    image_pusher:
      build: ./image_pusher
      restart: on-failure
      networks:
        - rmq
      depends_on:
        - rabbitmq
      container_name: image_pusher
      volumes:
          - ./image_pusher/images_to_process:/work/images_to_process/

    mean_color_calculator:
      build: ./mean_color_calculator
      restart: on-failure
      networks:
        - rmq
      depends_on:
        - rabbitmq
      container_name: mean_color_calculator

    image_classifier:
      build: ./image_classification
      restart: on-failure
      networks:
        - rmq
      depends_on:
        - rabbitmq
      container_name: image_classifier
      volumes:
        - ./image_classifier/processed_images:/work/processed_images/

networks:
  rmq: